### ISSUE TITLE
errors on startup

### ISSUE THREAD

**Issue by brothermechanic** [dairin0d/batch-operations#4]
bm@BM ~ $ blender
Read new prefs: /home/bm/.config/blender/2.78/config/userpref.blend
Traceback (most recent call last):
  File "/usr/share/blender/2.78/scripts/modules/addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "/usr/share/blender/2.78/scripts/addons/space_view3d_batch_operations/__init__.py", line 58, in <module>
    from . import batch_common
  File "/usr/share/blender/2.78/scripts/addons/space_view3d_batch_operations/batch_common.py", line 335, in <module>
    @addon.Operator(idname="object.batch_streamline_meshes", options={'REGISTER', 'UNDO'}, label="Streamline mesh(es)", description="Streamline mesh(es)", mode={'OBJECT', 'EDIT_MESH'})
  File "/usr/share/blender/2.78/scripts/addons/space_view3d_batch_operations/batch_common.py", line 385, in Operator_batch_streamline_meshes
    intersect_use_separate = BlRna.to_bpy_prop(bpy.ops.mesh.intersect, "use_separate")
  File "/usr/share/blender/2.78/scripts/addons/space_view3d_batch_operations/dairin0d/bpy_inspect.py", line 300, in to_bpy_prop
    rna_prop = (obj if name is None else BlRna(obj).properties[name])
KeyError: 'bpy_prop_collection[key]: key "use_separate" not found'

**Comment by brothermechanic** [comment]
blender-2.78.4 amd64 linux

**Comment by dairin0d** [comment]
Thanks! I fixed it.

**Comment by brothermechanic** [comment]
Works!
Thank you!
